export type LimitPermission =
  | 'article:create'
  | 'article:delete'
  | 'article:update'
  | 'draft:publish'
  | 'draft:create'
  | 'draft:delete'
  | 'draft:update'
  | 'document:create'
  | 'document:delete'
  | 'document:update'
  | 'img:delete';

export type Permission = LimitPermission | 'all';

export const permissionPathMap: Record<LimitPermission, string> = {
  'article:create': 'post-/api/admin/article',
  'article:delete': 'delete-/api/admin/article/:id',
  'article:update': 'put-/api/admin/article/:id',
  'draft:create': 'post-/api/admin/draft',
  'draft:publish': 'post-/api/admin/draft/publish',
  'draft:delete': 'delete-/api/admin/draft/:id',
  'draft:update': 'put-/api/admin/draft/:id',
  'document:create': 'post-/api/admin/document',
  'document:delete': 'delete-/api/admin/document/:id',
  'document:update': 'put-/api/admin/document/:id',
  'img:delete': 'delete-/api/admin/img/:sign',
};

export const pathPermissionMap: Record<string, LimitPermission> = {
  'post-/api/admin/article': 'article:create',
  'delete-/api/admin/article/:id': 'article:delete',
  'put-/api/admin/article/:id': 'article:update',
  'post-/api/admin/draft/publish': 'draft:publish',
  'post-/api/admin/draft': 'draft:create',
  'delete-/api/admin/draft/:id': 'draft:delete',
  'put-/api/admin/draft/:id': 'draft:update',
  'post-/api/admin/document': 'document:create',
  'delete-/api/admin/document/:id': 'document:delete',
  'put-/api/admin/document/:id': 'document:update',
  'delete-/api/admin/img/:sign': 'img:delete',
};

export const permissionRoutes = Object.values(permissionPathMap);

export const relatedPermissionRouteMap: Record<string, LimitPermission[]> = {
  'get-/api/admin/article': ['article:create', 'article:update', 'article:delete'],
  'get-/api/admin/article/:id': ['article:create', 'article:update', 'article:delete'],
  'get-/api/admin/article/search': ['article:create', 'article:update', 'article:delete'],
  'post-/api/admin/article/searchByLink': ['article:create', 'article:update', 'article:delete'],
  'get-/api/admin/draft': ['draft:create', 'draft:update', 'draft:delete', 'draft:publish'],
  'get-/api/admin/draft/:id': ['draft:create', 'draft:update', 'draft:delete', 'draft:publish'],
  'get-/api/admin/draft/search': ['draft:create', 'draft:update', 'draft:delete', 'draft:publish'],
  'get-/api/admin/document': ['document:create', 'document:update', 'document:delete'],
  'get-/api/admin/document/:id': ['document:create', 'document:update', 'document:delete'],
  'get-/api/admin/document/search': ['document:create', 'document:update', 'document:delete'],
  'get-/api/admin/document/tree': ['document:create', 'document:update', 'document:delete'],
  'get-/api/admin/document/libraries': ['document:create', 'document:update', 'document:delete'],
  'get-/api/admin/document/library/:id': [
    'document:create',
    'document:update',
    'document:delete',
  ],
  'get-/api/admin/document/library/:id/export': [
    'document:create',
    'document:update',
    'document:delete',
  ],
};

export const superAdminOnlyRoutePrefixes = [
  'get-/api/admin/token',
  'post-/api/admin/token',
  'put-/api/admin/token',
  'delete-/api/admin/token',
  'get-/api/admin/backup',
  'post-/api/admin/backup',
  'put-/api/admin/backup',
  'delete-/api/admin/backup',
  'get-/api/admin/auto-backup',
  'post-/api/admin/auto-backup',
  'put-/api/admin/auto-backup',
  'delete-/api/admin/auto-backup',
  'get-/api/admin/caddy',
  'post-/api/admin/caddy',
  'put-/api/admin/caddy',
  'delete-/api/admin/caddy',
  'get-/api/admin/collaborator',
  'post-/api/admin/collaborator',
  'put-/api/admin/collaborator',
  'delete-/api/admin/collaborator',
  'get-/api/admin/setting',
  'post-/api/admin/setting',
  'put-/api/admin/setting',
  'delete-/api/admin/setting',
  'get-/api/admin/customPage',
  'post-/api/admin/customPage',
  'put-/api/admin/customPage',
  'delete-/api/admin/customPage',
  'get-/api/admin/pipeline',
  'post-/api/admin/pipeline',
  'put-/api/admin/pipeline',
  'delete-/api/admin/pipeline',
  'get-/api/admin/isr',
  'post-/api/admin/isr',
  'put-/api/admin/isr',
  'delete-/api/admin/isr',
  'get-/api/admin/ai-tagging',
  'post-/api/admin/ai-tagging',
  'put-/api/admin/ai-tagging',
  'delete-/api/admin/ai-tagging',
  'get-/api/admin/analysis',
  'post-/api/admin/analysis',
  'put-/api/admin/analysis',
  'delete-/api/admin/analysis',
  'get-/api/admin/log',
  'post-/api/admin/log',
  'put-/api/admin/log',
  'delete-/api/admin/log',
  'get-/api/admin/icon',
  'post-/api/admin/icon',
  'put-/api/admin/icon',
  'delete-/api/admin/icon',
  'get-/api/admin/nav-category',
  'post-/api/admin/nav-category',
  'put-/api/admin/nav-category',
  'delete-/api/admin/nav-category',
  'get-/api/admin/nav-tool',
  'post-/api/admin/nav-tool',
  'put-/api/admin/nav-tool',
  'delete-/api/admin/nav-tool',
  'get-/api/admin/search',
  'post-/api/admin/search',
  'put-/api/admin/search',
  'delete-/api/admin/search',
  'put-/api/admin/auth',
  'post-/api/admin/auth/restore',
  'get-/api/admin/auth/debug-token',
  'get-/api/admin/meta/',
  'post-/api/admin/meta/',
  'put-/api/admin/meta/',
  'delete-/api/admin/meta/',
  'get-/api/admin/meta/about',
  'post-/api/admin/meta/about',
  'put-/api/admin/meta/about',
  'delete-/api/admin/meta/about',
  'get-/api/admin/meta/site',
  'post-/api/admin/meta/site',
  'put-/api/admin/meta/site',
  'delete-/api/admin/meta/site',
  'get-/api/admin/meta/menu',
  'post-/api/admin/meta/menu',
  'put-/api/admin/meta/menu',
  'delete-/api/admin/meta/menu',
  'get-/api/admin/meta/social',
  'post-/api/admin/meta/social',
  'put-/api/admin/meta/social',
  'delete-/api/admin/meta/social',
  'get-/api/admin/meta/link',
  'post-/api/admin/meta/link',
  'put-/api/admin/meta/link',
  'delete-/api/admin/meta/link',
  'get-/api/admin/meta/reward',
  'post-/api/admin/meta/reward',
  'put-/api/admin/meta/reward',
  'delete-/api/admin/meta/reward',
];

export const publicRoutes = [
  'get-/api/admin/meta',
  'post-/api/admin/auth/login',
  'post-/api/admin/auth/logout',
  'get-/api/admin/category/all',
  'get-/api/admin/tag/all',
  'get-/api/admin/img/all',
  'get-/api/admin/img',
  'get-/api/admin/collaborator/list',
  'post-/api/admin/img/upload',
];
