#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOST_DEV_DIR="${ROOT_DIR}/tests/host-dev"
HOST_RUNTIME_DIR="${HOST_DEV_DIR}/runtime"
MANUAL_RUNTIME_DIR="${ROOT_DIR}/tests/manual-v1.3.0/runtime"

mkdir -p \
  "${HOST_RUNTIME_DIR}/data/static" \
  "${HOST_RUNTIME_DIR}/log" \
  "${HOST_RUNTIME_DIR}/codeRunner" \
  "${HOST_RUNTIME_DIR}/pluginRunner" \
  "${HOST_RUNTIME_DIR}/pids"

export TZ="${TZ:-Asia/Shanghai}"
export NODE_ENV="${NODE_ENV:-development}"

export VAN_BLOG_DATABASE_URL="${VAN_BLOG_DATABASE_URL:-postgresql://postgres:postgres@127.0.0.1:15432/vanblog}"
export VAN_BLOG_REDIS_URL="${VAN_BLOG_REDIS_URL:-redis://127.0.0.1:16379}"
export VAN_BLOG_WALINE_DB="${VAN_BLOG_WALINE_DB:-waline}"
export VAN_BLOG_WALINE_DATABASE_URL="${VAN_BLOG_WALINE_DATABASE_URL:-postgresql://postgres:postgres@127.0.0.1:15432/${VAN_BLOG_WALINE_DB}}"
export VAN_BLOG_CADDY_MANAGE_HTTPS="${VAN_BLOG_CADDY_MANAGE_HTTPS:-false}"
export VAN_BLOG_DEBUG_SUPER_TOKEN="${VAN_BLOG_DEBUG_SUPER_TOKEN:-vanblog-debug-test}"
export VAN_BLOG_CLOUDFLARE_API_TOKEN="${VAN_BLOG_CLOUDFLARE_API_TOKEN:-}"
export VAN_BLOG_CLOUDFLARE_ZONE_ID="${VAN_BLOG_CLOUDFLARE_ZONE_ID:-}"
export VANBLOG_WEBSITE_CONTROL_URL="${VANBLOG_WEBSITE_CONTROL_URL:-http://127.0.0.1:3011}"
export VANBLOG_WALINE_CONTROL_URL="${VANBLOG_WALINE_CONTROL_URL:-http://127.0.0.1:8361}"
export VANBLOG_WEBSITE_ISR_BASE="${VANBLOG_WEBSITE_ISR_BASE:-http://127.0.0.1:3001/api/revalidate?path=}"
export VAN_BLOG_SERVER_URL="${VAN_BLOG_SERVER_URL:-http://127.0.0.1:3000}"
export VAN_BLOG_ALLOW_DOMAINS="${VAN_BLOG_ALLOW_DOMAINS:-pic.mereith.com,localhost,127.0.0.1}"
export WALINE_JWT_TOKEN="${WALINE_JWT_TOKEN:-vanblog-change-me}"
export WEBSITE_CONTROL_PORT="${WEBSITE_CONTROL_PORT:-3011}"
export WALINE_CONTROL_PORT="${WALINE_CONTROL_PORT:-8361}"
export HOST_DEV_HTTP_PORT="${HOST_DEV_HTTP_PORT:-18080}"
export HOST_DEV_LOG_DIR="${HOST_DEV_LOG_DIR:-${HOST_RUNTIME_DIR}/log}"
export PG_HOST="${PG_HOST:-127.0.0.1}"
export PG_PORT="${PG_PORT:-15432}"
export PG_DB="${PG_DB:-${VAN_BLOG_WALINE_DB}}"
export PG_USER="${PG_USER:-postgres}"
export PG_PASSWORD="${PG_PASSWORD:-postgres}"
export VAN_BLOG_STATIC_PATH="${VAN_BLOG_STATIC_PATH:-${MANUAL_RUNTIME_DIR}/data/static}"
export VAN_BLOG_LOG="${VAN_BLOG_LOG:-${HOST_RUNTIME_DIR}/log}"
export VAN_BLOG_CODE_RUNNER_PATH="${VAN_BLOG_CODE_RUNNER_PATH:-${HOST_RUNTIME_DIR}/codeRunner}"
export VAN_BLOG_PLUGIN_RUNNER_PATH="${VAN_BLOG_PLUGIN_RUNNER_PATH:-${HOST_RUNTIME_DIR}/pluginRunner}"
export BROWSER="${BROWSER:-none}"
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD="${PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD:-1}"
